services:
  vein-server:
    build: .
    container_name: vein-server
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "7777:7777/udp"
      - "27015:27015/udp"

    volumes:
      - ./data/serverfiles:/home/steam/server
      - ./data/saves:/home/steam/server/Saves
      - ./data/logs:/home/steam/server/Logs
      - ./data/config:/home/steam/server/Config
