services:
  scum-server:
    image: marcsbrooks/docker-scum-server:latest
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "${PORT_GAME_UDP}:7777/udp"
      - "${PORT_GAME_TCP}:7777/tcp"
      - "${PORT_QUERY_UDP}:7778/udp"
      - "${PORT_RCON_TCP}:7779/tcp"

    volumes:
      - ./data/serverfiles:/server
      - ./data/saves:/server/SERVER/Saved
      - ./data/logs:/server/logs
      - ./data/backups:/server/backups
      - ./data/config:/server/config
      - ./data/mods:/server/mods

    command: [ "/entrypoint.sh" ]
