services:
  valheim:
    image: lloesche/valheim-server:latest
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped

    network_mode: host

    environment:
      - SERVER_NAME=${SERVER_NAME}
      - WORLD_NAME=${WORLD_NAME}
      - SERVER_PASS=${SERVER_PASSWORD}
      - SERVER_PUBLIC=${SERVER_PUBLIC}
      - TZ=${TZ}

    volumes:
      - ./data/config:/config
      - ./data/worlds:/config/worlds
      - ./data/optvalheim:/opt/valheim
